platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Hera' do
    pod 'Reachability', '3.2'
    pod 'ZipArchive', '1.4.0'
    pod 'MJRefresh', '3.1.9'
    pod 'AFNetworking', '3.0'
end
